name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node (required by gh-pages)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install gh-pages tool
        run: npm install -g gh-pages

      - name: Copy files to build directory
        run: |
          mkdir dist
          cp index.html dist/

      - name: Deploy to gh-pages branch
        run: gh-pages -d dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
