name: Deploy static HTML to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Setup Pages
        uses: actions/configure-pages@v5  # Updated to v5

      - name: Upload site files
        uses: actions/upload-pages-artifact@v3  # Updated to v3
        with:
          path: .  # Ensure this points to the directory with your HTML files

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Updated to v4