name: Deploy static site using gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create dist folder with HTML
        run: |
          mkdir dist
          cp index.html dist/

      - name: Install gh-pages
        run: npm install -g gh-pages

      - name: Deploy to gh-pages
        run: gh-pages -d dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
